#!/usr/bin/env bash

# Solution to find Docker build dir taken from https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker build ${DIR} --target=base -t vimenv

# Cols/Lines fix as Docker doesn't always get the terminal size right initially.
# Solution taken from https://github.com/moby/moby/issues/33794#issuecomment-312873988
docker run -e COLUMNS="`tput cols`" -e LINES="`tput lines`" --rm -it -v ${PWD}:/workdir vimenv
